### ISSUE TITLE
How can I use PyPy as default language?

### ISSUE THREAD

**Issue by hppRC** [Tatamo/atcoder-cli#29]
I'm sorry but I can't understand how to set default language PyPy3.
Would you tell me how to set this?

**Comment by Tatamo** [comment]
@hppRC Sorry, atcoder-cli internally uses https://github.com/online-judge-tools/oj to submit, and currently atcoder-cli has no feature to pass extra argument s.t. `oj s --guess-python-interpreter pypy`.
I'll fix this problem in the next release.

**Comment by Tatamo** [comment]
I decided to released atcoder-cli@2.1.0, this version includes a feature to pass arguments to online-judge-tools.
Try `acc s main.py -- --guess-python-interpreter pypy` or `acc s --skip-filename -- --guess-python-interpreter pypy`.

I'll still thinking about the feature so that we can set some default arguments in template or something. (And I'm sorry to say that the above command may be changed and broken in future to integrate it in those future feature)

**Comment by hppRC** [comment]
Thanks!! 
It's completely useful for me and please don't worry about any breaking changes to develop advanced features of this great tool.
I'll check releases continuously.
